/*
 * File: Conteudo.ui.js
 * Date: Fri Jul 09 2010 15:54:57 GMT-0300 (BRT)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.1.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

ConteudoUi = Ext.extend(Ext.TabPanel, {
    activeTab: 2,
    width: 578,
    height: 366,
    initComponent: function() {
        this.items = [
            {
                xtype: 'panel',
                title: 'Tab 1',
                tbar: {
                    xtype: 'toolbar'
                }
            },
            {
                xtype: 'panel',
                title: 'Tab 2'
            },
            {
                xtype: 'panel',
                title: 'Tab 3'
            }
        ];
        ConteudoUi.superclass.initComponent.call(this);
    }
});
