/*
 * File: Detalhe.ui.js
 * Date: Fri Jul 09 2010 15:54:57 GMT-0300 (BRT)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.1.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

DetalheUi = Ext.extend(Ext.Panel, {
    autoScroll: true,
    title: 'Detalhe',
    initComponent: function() {
        DetalheUi.superclass.initComponent.call(this);
    }
});
