/*
 * File: Detalhe.js
 * Date: Fri Jul 09 2010 15:54:57 GMT-0300 (BRT)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.1.
 * http://www.extjs.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

Detalhe = Ext.extend(DetalheUi, {
    initComponent: function() {
        Detalhe.superclass.initComponent.call(this);
    }
});
Ext.reg('detalhe', Detalhe);