/*
 * File: PainelPrincipal.ui.js
 * Date: Tue Jun 29 2010 22:37:49 GMT-0300 (BRT)
 * 
 * This file was generated by Ext Designer version xds-1.0.1.0c.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

PainelPrincipalUi = Ext.extend(Ext.form.FormPanel, {
    title: 'Elo Group',
    labelWidth: 100,
    labelAlign: 'left',
    layout: 'border',
    width: 856,
    height: 700,
    padding: 10,
    autoHeight: false,
    autoWidth: true,
    titleCollapse: true,
    bodyBorder: false,
    hideBorders: false,
    footer: true,
    closable: false,
    initComponent: function() {
        this.items = [
            {
                xtype: 'panel',
                title: 'Navegação',
                layout: 'accordion',
                activeItem: 0,
                width: 200,
                height: 580,
                closable: true,
                region: 'west',
                hidden: false,
                hideMode: 'display',
                maskDisabled: true,
                split: true,
                collapsible: true,
                layoutConfig: {
                    collapseFirst: false
                },
                items: [
                    {
                        xtype: 'treepanel',
                        title: 'Grupos',
                        rootVisible: false,
                        root: {
                            text: 'Root Node'
                        },
                        loader: {

                        },
                        tbar: {
                            xtype: 'toolbar',
                            items: [
                                {
                                    xtype: 'button',
                                    text: 'Todos',
                                    ref: '../../../todosBtn'
                                },
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'button',
                                    text: 'Meus',
                                    ref: '../../../meusBtn'
                                }
                            ]
                        }
                    },
                    {
                        xtype: 'panel',
                        title: 'My Panel'
                    },
                    {
                        xtype: 'panel',
                        title: 'My Panel'
                    }
                ]
            },
            {
                xtype: 'panel',
                title: 'Principal',
                region: 'center',
                layout: 'accordion',
                activeItem: 0,
                split: false,
                tbar: {
                    xtype: 'toolbar',
                    items: [
                        {
                            xtype: 'button',
                            text: 'Sumário'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            text: 'Fórum',
                            menu: {
                                xtype: 'menu',
                                items: [
                                    {
                                        xtype: 'menuitem',
                                        text: 'Filtrar Tópicos'
                                    },
                                    {
                                        xtype: 'menuitem',
                                        text: 'Publicar Novo Tópico'
                                    }
                                ]
                            }
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            text: 'Eventos',
                            menu: {
                                xtype: 'menu',
                                items: [
                                    {
                                        xtype: 'menuitem',
                                        text: 'Filtrar Eventos'
                                    },
                                    {
                                        xtype: 'menuitem',
                                        text: 'Publicar Novo Evento'
                                    }
                                ]
                            }
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            text: 'Arquivos',
                            menu: {
                                xtype: 'menu',
                                items: [
                                    {
                                        xtype: 'menuitem',
                                        text: 'Filtrar Arquivos'
                                    },
                                    {
                                        xtype: 'menuitem',
                                        text: 'Publicar Novo Arquivo'
                                    }
                                ]
                            }
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            text: 'Seguidores',
                            menu: {
                                xtype: 'menu',
                                items: [
                                    {
                                        xtype: 'menuitem',
                                        text: 'Ver Seguidores do Grupo'
                                    },
                                    {
                                        xtype: 'menuitem',
                                        text: 'Enviar Mensagem a um Seguidor'
                                    }
                                ]
                            }
                        }
                    ]
                },
                items: [
                    {
                        xtype: 'panel',
                        title: 'Descrição do Grupo',
                        height: 100,
                        autoHeight: true,
                        activeTab: 1
                    },
                    {
                        xtype: 'grid',
                        title: 'Sumário',
                        region: 'center',
                        autoExpandColumn: 1,
                        columns: [
                            {
                                xtype: 'gridcolumn',
                                header: 'Título',
                                sortable: true,
                                resizable: true,
                                dataIndex: 'string',
                                align: 'center',
                                id: 1
                            },
                            {
                                xtype: 'datecolumn',
                                header: 'Data',
                                sortable: true,
                                resizable: true,
                                width: 100,
                                format: 'm/d/Y',
                                dataIndex: 'date',
                                align: 'center'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'panel',
                title: 'Detalhe',
                region: 'east',
                width: 500,
                autoScroll: true,
                split: true
            }
        ];
        PainelPrincipalUi.superclass.initComponent.call(this);
    }
});
