/*
 * File: PainelPrincipal.js
 * Date: Thu Jun 24 2010 19:01:23 GMT-0300 (BRT)
 * 
 * This file was generated by Ext Designer version xds-1.0.1.0c.
 * http://www.extjs.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

PainelPrincipal = Ext.extend(PainelPrincipalUi, {
    initComponent: function() {
        PainelPrincipal.superclass.initComponent.call(this);
    }
});
