/*
 * File: Principal.ui.js
 * Date: Thu Jul 29 2010 15:03:53 GMT-0300 (BRT)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.11.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

PrincipalUi = Ext.extend(Ext.Panel, {
    title: 'Principal',
    layout: 'accordion',
    width: 725,
    height: 514,
    activeItem: 0,
    initComponent: function() {
        this.tbar = {
            xtype: 'toolbar',
            items: [
                {
                    xtype: 'splitbutton',
                    text: 'Sumário',
                    icon: 'icons/add.png'
                },
                {
                    xtype: 'tbseparator'
                },
                {
                    xtype: 'splitbutton',
                    text: 'Fórum',
                    menu: {
                        xtype: 'menu',
                        items: [
                            {
                                xtype: 'menuitem',
                                text: 'Filtrar Tópicos'
                            },
                            {
                                xtype: 'menuitem',
                                text: 'Publicar Novo Tópico'
                            }
                        ]
                    }
                },
                {
                    xtype: 'tbseparator'
                },
                {
                    xtype: 'splitbutton',
                    text: 'Eventos',
                    menu: {
                        xtype: 'menu',
                        items: [
                            {
                                xtype: 'menuitem',
                                text: 'Filtrar Eventos'
                            },
                            {
                                xtype: 'menuitem',
                                text: 'Publicar Novo Evento'
                            }
                        ]
                    }
                },
                {
                    xtype: 'tbseparator'
                },
                {
                    xtype: 'splitbutton',
                    text: 'Arquivos',
                    menu: {
                        xtype: 'menu',
                        items: [
                            {
                                xtype: 'menuitem',
                                text: 'Filtrar Arquivos'
                            },
                            {
                                xtype: 'menuitem',
                                text: 'Publicar Novo Arquivo'
                            }
                        ]
                    }
                },
                {
                    xtype: 'tbseparator'
                },
                {
                    xtype: 'splitbutton',
                    text: 'Seguidores',
                    menu: {
                        xtype: 'menu',
                        items: [
                            {
                                xtype: 'menuitem',
                                text: 'Ver Seguidores do Grupo'
                            },
                            {
                                xtype: 'menuitem',
                                text: 'Enviar Mensagem a um Seguidor'
                            }
                        ]
                    }
                }
            ]
        };
        this.items = [
            {
                xtype: 'panel',
                title: 'Descrição',
                height: 200
            },
            {
                xtype: 'panel',
                title: 'Sumário'
            }
        ];
        PrincipalUi.superclass.initComponent.call(this);
    }
});
