/*
 * File: xds_index.js
 * Date: Thu Jun 17 2010 16:11:20 GMT-0300 (BRT)
 * 
 * This file was generated by Ext Designer version xds-1.0.1.0c.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.onReady(function() {
    var navegacao = new Navegacao({
        renderTo: Ext.getBody()
    });
    navegacao.show();
});
