/*
 * File: xds_index.js
 * Date: Fri Jul 09 2010 16:01:19 GMT-0300 (BRT)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.1.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.onReady(function() {
    var painelPrincipal = new PainelPrincipal({
        renderTo: Ext.getBody()
    });
    painelPrincipal.show();
    var conteudo = new Conteudo({
        renderTo: Ext.getBody()
    });
    conteudo.show();
});
