/*
 * File: xds_index.js
 * Date: Tue Jun 29 2010 22:37:49 GMT-0300 (BRT)
 * 
 * This file was generated by Ext Designer version xds-1.0.1.0c.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.onReady(function() {
    var painelPrincipal = new PainelPrincipal({
        renderTo: Ext.getBody()
    });
    painelPrincipal.show();
});
